from reportlab.pdfgen import canvas
import os
from helper_functions import get_npy_images
import cv2
from segment_scans import full_segmentation_pipeline
from character_analysis import full_classification_pipeline
import numpy
from prepare_scans import get_skeletons
base_pdf_folder= r"C:\Users\rafee\PycharmProjects\handwriting-project-epq\pdf_intermediate"
images_prepared_base_folder = r"C:\Users\rafee\PycharmProjects\handwriting-project-epq\images\images_lines_removed"

labels_to_numbers = {
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    'A': 10,
    'B': 11,
    'C': 12,
    'D': 13,
    'E': 14,
    'F': 15,
    'G': 16,
    'H': 17,
    'I': 18,
    'J': 19,
    'K': 20,
    'L': 21,
    'M': 22,
    'N': 23,
    'O': 24,
    'P': 25,
    'Q': 26,
    'R': 27,
    'S': 28,
    'T': 29,
    'U': 30,
    'V': 31,
    'W': 32,
    'X': 33,
    'Y': 34,
    'Z': 35,
    'a': 36,
    'b': 37,
    'd': 38,
    'e': 39,
    'f': 40,
    'g': 41,
    'h': 42,
    'n': 43,
    'q': 44,
    'r': 45,
    't': 46,
    '!': 47,
    '(': 48,
    ')': 49,
    '+': 50,
    ',': 51,
    '-': 52,
    '=': 53,
    '[': 54,
    ']': 55,
    'alpha': 56,
    'ascii_124': 57,
    'beta': 58,
    'Delta': 59,
    'div': 60,
    'exists': 61,
    'forall': 62,
    'forward_slash': 63,
    'gamma': 64,
    'gt': 65,
    'in': 66,
    'infty': 67,
    'int': 68,
    'lambda': 69,
    'lt': 70,
    'mu': 71,
    'neq': 72,
    'phi': 73,
    'pi': 74,
    'prime': 75,
    'rightarrow': 76,
    'sigma': 77,
    'sqrt': 78,
    'sum': 79,
    'theta': 80,
    'times': 81,
    '{': 82,
    '}': 83
}
numbers_to_labels = {
    0: '0',
    1: '1',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: 'A',
    11: 'B',
    12: 'C',
    13: 'D',
    14: 'E',
    15: 'F',
    16: 'G',
    17: 'H',
    18: 'I',
    19: 'J',
    20: 'K',
    21: 'L',
    22: 'M',
    23: 'N',
    24: 'O',
    25: 'P',
    26: 'Q',
    27: 'R',
    28: 'S',
    29: 'T',
    30: 'U',
    31: 'V',
    32: 'W',
    33: 'X',
    34: 'Y',
    35: 'Z',
    36: 'a',
    37: 'b',
    38: 'd',
    39: 'e',
    40: 'f',
    41: 'g',
    42: 'h',
    43: 'n',
    44: 'q',
    45: 'r',
    46: 't',
    47: '!',
    48: '(',
    49: ')',
    50: '+',
    51: ',',
    52: '-',
    53: '=',
    54: '[',
    55: ']',
    56: 'alpha',
    57: 'ascii_124',
    58: 'beta',
    59: 'Delta',
    60: 'div',
    61: 'exists',
    62: 'forall',
    63: 'forward_slash',
    64: 'gamma',
    65: 'gt',
    66: 'in',
    67: 'infty',
    68: 'int',
    69: 'lambda',
    70: 'lt',
    71: 'mu',
    72: 'neq',
    73: 'phi',
    74: 'pi',
    75: 'prime',
    76: 'rightarrow',
    77: 'sigma',
    78: 'sqrt',
    79: 'sum',
    80: 'theta',
    81: 'times',
    82: '{',
    83: '}'
}
letter_type_to_letter = {
    '0': "0",
    '1': "1",
    '2': "2",
    '3': "3",
    '4': "4",
    '5': "5",
    '6': "6",
    '7': "7",
    '8': "8",
    '9': "9",
    'A': "A",
    'B': "B",
    'C': "C",
    'D': "D",
    'E': "E",
    'F': "F",
    'G': "G",
    'H': "H",
    'I': "I",
    'J': "J",
    'K': "K",
    'L': "L",
    'M': "M",
    'N': "N",
    'O': "O",
    'P': "P",
    'Q': "Q",
    'R': "R",
    'S': "S",
    'T': "T",
    'U': "U",
    'V': "V",
    'W': "W",
    'X': "X",
    'Y': "Y",
    'Z': "Z",
    'a': "a",
    'b': "b",
    'd': "d",
    'e': "e",
    'f': "f",
    'g': "g",
    'h': "h",
    'n': "n",
    'q': "q",
    'r': "r",
    't': "t",
    '!': "!",
    '(': "(",
    ')': ")",
    '+': "+",
    ',': ",",
    '-': "—",
    '=': "=",
    '[': "[",
    ']': "]",
    'alpha': "α",
    'ascii_124': "|",
    'beta': "β",
    'Delta': "Δ",
    'div': "÷",
    'exists': "∃",
    'forall': "∀",
    'forward_slash': "/",
    'gamma': "γ",
    'gt': ">",
    'in': "∈",
    'infty': "∞",
    'int': "∫",
    'lambda': "λ",
    'lt': "<",
    'mu': "μ",
    'neq': "≠",
    'phi': "ϕ",
    'pi': "π",
    'prime': "′",
    'rightarrow': "→",
    'sigma': "σ",
    'sqrt': "√",
    'sum': "Σ",
    'theta': "θ",
    'times': "×",
    '{': "{",
    '}': "}"
}

def get_standardised_info(letter_real_height, letter_real_width, letter_real_y):
    line_to_snap_to = round(letter_real_y/30, 0)
    y_to_snap_to = line_to_snap_to * 30 #These two lines find the nearest y line to snap to
    average_proportion = max(letter_real_height, letter_real_width)
    font_size = int(average_proportion / 0.7) #This determines the font size based off whichever dimension of the letter is largest
    return y_to_snap_to, font_size

def draw_letters_to_pdf(letter_information_lists, file_name):
    images_prepared_filepath = os.path.join(images_prepared_base_folder, file_name+".png")
    original_page_height, original_page_width = cv2.imread(images_prepared_filepath, 2).shape
    c = canvas.Canvas(os.path.join(base_pdf_folder, file_name+".pdf"), pagesize=(original_page_width, original_page_height)) #Initialises a new pdf as the 'canvas'
    for letter in letter_information_lists:
        letter_type = letter[0]
        letter_bottom_left = letter[1]
        letter_real_y = original_page_height - letter_bottom_left[1] #these pdfs count y from the bottom up, so you need to inverse it to get 'real' height
        letter_real_height = letter[2]
        letter_real_width = letter[3]
        y_to_snap_to, letter_font_size = get_standardised_info(letter_real_height, letter_real_width, letter_real_y) #Gets the y value and font size correct
        c.setFont("Times-Roman", letter_font_size)
        if letter_type == "-":
            letter_font_size = letter_font_size * 2
        c.drawString(letter_bottom_left[0], y_to_snap_to, letter_type_to_letter[str(letter_type)]) #Draws the letter with the y value and font calculated in the above function
    c.save() #c.save is always necessary as the functions work on a shadow copy of the pdf so without this the changes will not be visble

def get_letter_information_lists(filename):
    components, normalised_skeletons = get_skeletons(filename)
    numpy_skeletons = numpy.array(normalised_skeletons) #This gets the skeletons of the characters in an image
    predictions = full_classification_pipeline(numpy_skeletons) #Gets the prediction per letter, including user input where applicable
    letter_information_lists = []
    for index in range(0, len(components)): #For each component, it accesses the prediction associated with that component, along with its coordinates, for use in the drawing function
        component = components[index]
        prediction = predictions[index]
        component_x_coordinate = component.x
        component_y_coordinate = component.y+component.height
        letter_information_list = [numbers_to_labels[prediction], (component_x_coordinate, component_y_coordinate), component.height, component.width]
        letter_information_lists.append(letter_information_list)
    return letter_information_lists #Returns a whole list of characters to draw and coordinates to (be processed into coordinates to) draw them at
